### ISSUE TITLE
Is there a certain correlation between the number of erolments and the local epidemic situation？

### ISSUE THREAD

**Issue by IlldanBZM** [lzw0409/DS4SMAP#1]
These three runs of the course were happend in 4/6, 6/29 and 10/5, and their erolments are 40299, 3181 and 1823. From the public data, we can learn there was a outbreaks of epidemic in the UK in April. So I guess the course situation was related to the epidemic situation.

**Comment by Llewellyn18** [comment]
Great insight, Ziming. I think this is quite an interesting issue that we can explore further. To figure out this issue, I think we should refer to more outside data to support our hypotheses.

**Comment by Llewellyn18** [comment]
If there are no more questions over this issue, I'm going to close it.
