### ISSUE TITLE
Write up reflections 

### ISSUE THREAD

**Issue by Llewellyn18** [lzw0409/DS4SMAP#3]
Hi, guys, should we write up our own reflection on the analysis parts that each one is in charge of and finally compile them up?@Fujifj @lzw0409 @IlldanBZM @Llewellyn18

**Comment by Llewellyn18** [comment]
I have uploaded my reflection. Guys, you can have a look.

**Comment by IlldanBZM** [comment]
It is a good idea, the reflections can help everyone understand other's work.

**Comment by Fujifj** [comment]
If we can do this, that will be great. Besides, I think we also need to talk about the challenge which we face when we analyze the data. For example, using python to make a world map needs to configure lots of library install and activate the extensions.

**Comment by s2122573** [comment]
It's ok if we spearate report into different parts. everyone could share their comments. maybe different opinions as well. so agree
