### ISSUE TITLE
report requirements

### ISSUE THREAD

**Issue by Llewellyn18** [lzw0409/DS4SMAP#4]
What elements need to be included in the report?

**Comment by IlldanBZM** [comment]
Generally speaking, we can find the source of problem, research methods and conclusions in a report. Considering our study, maybe the research method should be closer to the analysis process.

**Comment by Llewellyn18** [comment]
Yeah, I agree with you. We can divide our analysis process into four parts: comment analysis, enrolment and engagement data, student demographics, and course content introduction.

**Comment by lzw0409** [comment]
We should include host's concern and the goal host want to reach in the repost as well so it's more clear why we are doing what do and show if our research reach the goal host want us to complete.

**Comment by s2122573** [comment]
Also need to think of who are our finial target group. Adjust our direction . and make sure data host and potential stdents all understand clearly what we expressing. I think so far we did great. cheers
