### ISSUE TITLE
What kind of visualization graph can better analyze the excel worksheet named Learners who visited steps?

### ISSUE THREAD

**Issue by Fujifj** [lzw0409/DS4SMAP#7]
Hey, guys. I would like to use the heatmap to find out the relationship between the different columns of excel worksheet named Learners who visited steps. How about this idea?

**Comment by IlldanBZM** [comment]
Heatmap may be a method, but it would be difficult to distinguish the colors that represent large numbers by our eyes. I think funnel diagram is a better method.
